### PR TITLE
Single and Completable converters

### PR DESCRIPTION
**Pull request by akarnokd**
This PR adds direct converters to and from `Completable` and `Single`.

### CODE REVIEW

**Comment by ldaley** [comment]
@benjchristensen are you still the owner here? If not, who should be considered the new owner?

**Comment by benjchristensen** [comment]
I'm not actively engaged and don't have the ability to commit appropriate attention. @stevegury, @stealthcode, or @akarnokd can do anything needed.

**Comment by stevegury** [comment]
👍 
@akarnokd Do you have member acess on this repo (can you merge?)

**Comment by akarnokd** [comment]
Yes.

**Pull request merged**
